### ISSUE TITLE
Manually comiting offset

### ISSUE THREAD

**Issue by cyriltovena** [hoppity/kafka-basic#17]
Hello,

I've made the auto-commit option available and also implement a commit offset in the consumer based on your code, I've also reference the main branch from Microsoft.

Right now when auto commit is off and if I'm manually commiting after each message with the current offset read, once I restart my consummer it start back from offset zero, it looks like an offset reset is happening do you know why ?

Do you think using manual commit is a good idea of a consummer implementation ? Basically I wanted that if a message processing is failing, commit would not happen and the thread would be rebalanced and start back where it was.

**Comment by cyriltovena** [comment]
Could it be related with this https://github.com/Microsoft/Kafkanet/commit/186b9cd2c39d7e3b93404542259c337abe2ac71e

**Comment by cyriltovena** [comment]
Sorry when I implemented the commitoffset I did this mistake

``` csharp
public void Commit(string topic, int partition, long offset, bool setposition)
        {
            _instance.Commit(topic,partition, partition, setposition);
        }
```

Closing it. I'm still interested in your oponion about manual commit.

**Comment by ducas** [comment]
Hi @kuqd. The problem I have with manual commits after each message is that with the throughput you can get with Kafka, the sub-millisecond it takes to perform a commit can drastically increase the amount of time it takes to process the large amount of messages making their way through. I think that taking batches based on a period of time and committing after those is fine - hence the implementation of the BatchedConsumer. Otherwise I think simply having an autocommit interval should suffice.
Also, keep in mind there is currently an issue in the kafkanet library with committing offsets that are not in alignment with other libraries. Once that is resolved you would actually be committing the offset of the last received message + 1…

**Comment by cyriltovena** [comment]
Thank for the info,it's actually working for me, I did merge their fix though about alignment, before that it was causing a re-balancing.

You're right I definitively feel the system slower, but in my case it's for a bank(ish) system, so I can't miss a message at the price of performance which is fine.
